[package]
name = "actix-async"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix-rt = { git = "https://github.com/fakeshadow/actix-net.git", branch = "mio-0.7.3" }
async-trait = "0.1.41"
futures-util = "0.3.8"
slab = "0.4.2"
tokio = { version = "0.3.3", features = ["macros", "sync"] }

[dev-dependencies]
async-std = { version = "1.7.0", features = ["attributes", "unstable"] }